name: "Deploy to Vercel"

concurrency:
  cancel-in-progress: false
  group: "vercel"

on:
  # Uncomment to enable automatic deployments on push to main
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v5"

      - name: "Install Just command runner"
        uses: "extractions/setup-just@v3"
        with:
          just-version: "1"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"

      - name: "Install dependencies"
        run: "bun install"

      - name: "Run code checks"
        run: "just full-check"

      - name: "Pull Vercel environment"
        run: "bun vercel pull --environment=production --token=$VERCEL_TOKEN --yes"

      - name: "Build app using Vercel"
        env:
          NEXT_TELEMETRY_DISABLED: true
        run: "bun vercel build --prod --token=$VERCEL_TOKEN"

      - name: "Deploy app to Vercel"
        run: "bun vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN"

      - name: "Add summary"
        run: | # shell
          echo "## Deploy result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
